Feat/158/multi version
python-discord/snekbox pull request #181
Opened 2023-08-20 03:44 UTC by MarkKoz

Closes #175
This is an alternative implementation to #178 

Currently, this is a draft that just focuses on getting multiple Python interpreter versions into the image. Later, this PR will be updated with API changes as well. The goal for the API is for users to be able to pass an arbitrary path to an executable binary (e.g. a path to a different Python interpreter).

```
du -h --max-depth=1 /lang/python
93M	/lang/python/3.11
88M	/lang/python/3.12
181M	/lang/python
```

I observed smaller sizes (~70 MB) on Debian 12 (bookworm), but I've had trouble with test failures on bookworm, so the image remains on Debian 11 (buster) for now.

2023-08-23 12:04 UTC, ChrisLovering commented
FWIW, I think this is a good approach as far as the image is concerned.

2023-08-26 21:15 UTC, ChrisLovering approved these changes

2023-08-29 17:08 UTC, MarkKoz commented on deployment.yaml
> +                    {}/bin/python -m pip install -U
Yes, good catch. Also I think the env var needs to use `export`.

2023-08-29 17:31 UTC, jb3 requested changes
all looks good and works locally -- just needs the `--user` change for deps and should be good to go!

2023-08-29 17:31 UTC, jb3 commented on deployment.yaml
> +                    {}/bin/python -m pip install -U
```suggestion
                    find /lang/python -mindepth 1 -maxdepth 1 -type d -exec
                    PYTHONUSERBASE=/snekbox/user_base &&
                    {}/bin/python -m pip install --user -U
```

2023-08-29 18:06 UTC, ChrisLovering approved these changes

2023-08-29 18:35 UTC, merged